baseURL: "https://www.gmreads.com"
title: Meditations 
pagination:
  pagerSize: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true

markup:
  goldmark:
    renderer:
      unsafe: true

menu:
     main:
         - name: Archives 
           url: archives/
           weight: 5
         - name: Tags
           url: tags/
           weight: 10
         - name: Categories
           url: categories/
           weight: 15
         - name: Contact
           url: contact
           weight: 15

params:
    env: production
    defaultTheme: auto
    ShowReadingTime: true
    mainSections:
        - fitness
        - literature
        - compsci
        - personalfinance

    homeInfoParams:
        Title: "Meditations"
        Content: |
            Notes, book summaries, and thoughts on Fitness, Literature, Computer Science, Personal finance.

            Yes, the name is inspired from the book Meditations by Marcus Aurelius (Highly recommended!)
                
